package com.waheed.artificerx.core.plugin

/** Rich first-party capability registry. Entries represent real app modules/capability contracts, not fake marketplace cards. */
object BuiltinPluginCatalog {
    val plugins: List<PluginDescriptor> = buildList {
        add(descriptor("ai_provider.openai.compatible", "OpenAI Compatible", PluginCategory.AI_PROVIDER, listOf("openai compatible", "discoverable", "configurable"), "Ai Provider"))
        add(descriptor("ai_provider.openrouter", "OpenRouter", PluginCategory.AI_PROVIDER, listOf("openrouter", "discoverable", "configurable"), "Ai Provider"))
        add(descriptor("ai_provider.groq", "Groq", PluginCategory.AI_PROVIDER, listOf("groq", "discoverable", "configurable"), "Ai Provider"))
        add(descriptor("ai_provider.cloudflare.ai", "Cloudflare AI", PluginCategory.AI_PROVIDER, listOf("cloudflare ai", "discoverable", "configurable"), "Ai Provider"))
        add(descriptor("ai_provider.local.inference", "Local Inference", PluginCategory.AI_PROVIDER, listOf("local inference", "discoverable", "configurable"), "Ai Provider"))
        add(descriptor("ai_provider.provider.fallback", "Provider Fallback", PluginCategory.AI_PROVIDER, listOf("provider fallback", "discoverable", "configurable"), "Ai Provider"))
        add(descriptor("ai_provider.provider.health", "Provider Health", PluginCategory.AI_PROVIDER, listOf("provider health", "discoverable", "configurable"), "Ai Provider"))
        add(descriptor("ai_provider.credential.vault", "Credential Vault", PluginCategory.AI_PROVIDER, listOf("credential vault", "discoverable", "configurable"), "Ai Provider"))
        add(descriptor("ai_provider.rate.limit.monitor", "Rate Limit Monitor", PluginCategory.AI_PROVIDER, listOf("rate limit monitor", "discoverable", "configurable"), "Ai Provider"))
        add(descriptor("ai_provider.endpoint.tester", "Endpoint Tester", PluginCategory.AI_PROVIDER, listOf("endpoint tester", "discoverable", "configurable"), "Ai Provider"))
        add(descriptor("ai_provider.vision.provider", "Vision Provider", PluginCategory.AI_PROVIDER, listOf("vision provider", "discoverable", "configurable"), "Ai Provider"))
        add(descriptor("ai_provider.reasoning.provider", "Reasoning Provider", PluginCategory.AI_PROVIDER, listOf("reasoning provider", "discoverable", "configurable"), "Ai Provider"))
        add(descriptor("model.model.router", "Model Router", PluginCategory.MODEL, listOf("model router", "discoverable", "configurable"), "Model"))
        add(descriptor("model.model.profiles", "Model Profiles", PluginCategory.MODEL, listOf("model profiles", "discoverable", "configurable"), "Model"))
        add(descriptor("model.context.budgeter", "Context Budgeter", PluginCategory.MODEL, listOf("context budgeter", "discoverable", "configurable"), "Model"))
        add(descriptor("model.token.meter", "Token Meter", PluginCategory.MODEL, listOf("token meter", "discoverable", "configurable"), "Model"))
        add(descriptor("model.reasoning.controls", "Reasoning Controls", PluginCategory.MODEL, listOf("reasoning controls", "discoverable", "configurable"), "Model"))
        add(descriptor("model.vision.models", "Vision Models", PluginCategory.MODEL, listOf("vision models", "discoverable", "configurable"), "Model"))
        add(descriptor("model.embedding.models", "Embedding Models", PluginCategory.MODEL, listOf("embedding models", "discoverable", "configurable"), "Model"))
        add(descriptor("model.prompt.presets", "Prompt Presets", PluginCategory.MODEL, listOf("prompt presets", "discoverable", "configurable"), "Model"))
        add(descriptor("model.model.benchmark", "Model Benchmark", PluginCategory.MODEL, listOf("model benchmark", "discoverable", "configurable"), "Model"))
        add(descriptor("model.model.health", "Model Health", PluginCategory.MODEL, listOf("model health", "discoverable", "configurable"), "Model"))
        add(descriptor("model.auto.model.select", "Auto Model Select", PluginCategory.MODEL, listOf("auto model select", "discoverable", "configurable"), "Model"))
        add(descriptor("model.model.aliases", "Model Aliases", PluginCategory.MODEL, listOf("model aliases", "discoverable", "configurable"), "Model"))
        add(descriptor("image_generation.image.generation", "Image Generation", PluginCategory.IMAGE_GENERATION, listOf("image generation", "discoverable", "configurable"), "Image Generation"))
        add(descriptor("image_generation.image.variations", "Image Variations", PluginCategory.IMAGE_GENERATION, listOf("image variations", "discoverable", "configurable"), "Image Generation"))
        add(descriptor("image_generation.image.upscaler", "Image Upscaler", PluginCategory.IMAGE_GENERATION, listOf("image upscaler", "discoverable", "configurable"), "Image Generation"))
        add(descriptor("image_generation.image.analyzer", "Image Analyzer", PluginCategory.IMAGE_GENERATION, listOf("image analyzer", "discoverable", "configurable"), "Image Generation"))
        add(descriptor("image_generation.prompt.enhancer", "Prompt Enhancer", PluginCategory.IMAGE_GENERATION, listOf("prompt enhancer", "discoverable", "configurable"), "Image Generation"))
        add(descriptor("image_generation.negative.prompt.studio", "Negative Prompt Studio", PluginCategory.IMAGE_GENERATION, listOf("negative prompt studio", "discoverable", "configurable"), "Image Generation"))
        add(descriptor("image_generation.aspect.ratio.lab", "Aspect Ratio Lab", PluginCategory.IMAGE_GENERATION, listOf("aspect ratio lab", "discoverable", "configurable"), "Image Generation"))
        add(descriptor("image_generation.style.presets", "Style Presets", PluginCategory.IMAGE_GENERATION, listOf("style presets", "discoverable", "configurable"), "Image Generation"))
        add(descriptor("image_generation.image.batch", "Image Batch", PluginCategory.IMAGE_GENERATION, listOf("image batch", "discoverable", "configurable"), "Image Generation"))
        add(descriptor("image_generation.image.gallery", "Image Gallery", PluginCategory.IMAGE_GENERATION, listOf("image gallery", "discoverable", "configurable"), "Image Generation"))
        add(descriptor("image_generation.image.metadata", "Image Metadata", PluginCategory.IMAGE_GENERATION, listOf("image metadata", "discoverable", "configurable"), "Image Generation"))
        add(descriptor("image_generation.image.export", "Image Export", PluginCategory.IMAGE_GENERATION, listOf("image export", "discoverable", "configurable"), "Image Generation"))
        add(descriptor("code.code.workspace", "Code Workspace", PluginCategory.CODE, listOf("code workspace", "discoverable", "configurable"), "Code"))
        add(descriptor("code.code.search", "Code Search", PluginCategory.CODE, listOf("code search", "discoverable", "configurable"), "Code"))
        add(descriptor("code.patch.engine", "Patch Engine", PluginCategory.CODE, listOf("patch engine", "discoverable", "configurable"), "Code"))
        add(descriptor("code.diff.viewer", "Diff Viewer", PluginCategory.CODE, listOf("diff viewer", "discoverable", "configurable"), "Code"))
        add(descriptor("code.refactor.assistant", "Refactor Assistant", PluginCategory.CODE, listOf("refactor assistant", "discoverable", "configurable"), "Code"))
        add(descriptor("code.test.generator", "Test Generator", PluginCategory.CODE, listOf("test generator", "discoverable", "configurable"), "Code"))
        add(descriptor("code.build.diagnostics", "Build Diagnostics", PluginCategory.CODE, listOf("build diagnostics", "discoverable", "configurable"), "Code"))
        add(descriptor("code.dependency.advisor", "Dependency Advisor", PluginCategory.CODE, listOf("dependency advisor", "discoverable", "configurable"), "Code"))
        add(descriptor("code.syntax.inspector", "Syntax Inspector", PluginCategory.CODE, listOf("syntax inspector", "discoverable", "configurable"), "Code"))
        add(descriptor("code.project.scaffolder", "Project Scaffolder", PluginCategory.CODE, listOf("project scaffolder", "discoverable", "configurable"), "Code"))
        add(descriptor("code.code.formatter", "Code Formatter", PluginCategory.CODE, listOf("code formatter", "discoverable", "configurable"), "Code"))
        add(descriptor("code.snippet.library", "Snippet Library", PluginCategory.CODE, listOf("snippet library", "discoverable", "configurable"), "Code"))
        add(descriptor("file.file.explorer", "File Explorer", PluginCategory.FILE, listOf("file explorer", "discoverable", "configurable"), "File"))
        add(descriptor("file.file.search", "File Search", PluginCategory.FILE, listOf("file search", "discoverable", "configurable"), "File"))
        add(descriptor("file.file.watcher", "File Watcher", PluginCategory.FILE, listOf("file watcher", "discoverable", "configurable"), "File"))
        add(descriptor("file.safe.copy", "Safe Copy", PluginCategory.FILE, listOf("safe copy", "discoverable", "configurable"), "File"))
        add(descriptor("file.safe.move", "Safe Move", PluginCategory.FILE, listOf("safe move", "discoverable", "configurable"), "File"))
        add(descriptor("file.file.diff", "File Diff", PluginCategory.FILE, listOf("file diff", "discoverable", "configurable"), "File"))
        add(descriptor("file.folder.packager", "Folder Packager", PluginCategory.FILE, listOf("folder packager", "discoverable", "configurable"), "File"))
        add(descriptor("file.checksum.tool", "Checksum Tool", PluginCategory.FILE, listOf("checksum tool", "discoverable", "configurable"), "File"))
        add(descriptor("file.text.preview", "Text Preview", PluginCategory.FILE, listOf("text preview", "discoverable", "configurable"), "File"))
        add(descriptor("file.binary.inspector", "Binary Inspector", PluginCategory.FILE, listOf("binary inspector", "discoverable", "configurable"), "File"))
        add(descriptor("file.metadata.inspector", "Metadata Inspector", PluginCategory.FILE, listOf("metadata inspector", "discoverable", "configurable"), "File"))
        add(descriptor("file.workspace.index", "Workspace Index", PluginCategory.FILE, listOf("workspace index", "discoverable", "configurable"), "File"))
        add(descriptor("export.artifact.export", "Artifact Export", PluginCategory.EXPORT, listOf("artifact export", "discoverable", "configurable"), "Export"))
        add(descriptor("export.zip.builder", "ZIP Builder", PluginCategory.EXPORT, listOf("zip builder", "discoverable", "configurable"), "Export"))
        add(descriptor("export.json.export", "JSON Export", PluginCategory.EXPORT, listOf("json export", "discoverable", "configurable"), "Export"))
        add(descriptor("export.markdown.export", "Markdown Export", PluginCategory.EXPORT, listOf("markdown export", "discoverable", "configurable"), "Export"))
        add(descriptor("export.svg.export", "SVG Export", PluginCategory.EXPORT, listOf("svg export", "discoverable", "configurable"), "Export"))
        add(descriptor("export.png.export", "PNG Export", PluginCategory.EXPORT, listOf("png export", "discoverable", "configurable"), "Export"))
        add(descriptor("export.pdf.export", "PDF Export", PluginCategory.EXPORT, listOf("pdf export", "discoverable", "configurable"), "Export"))
        add(descriptor("export.project.bundle", "Project Bundle", PluginCategory.EXPORT, listOf("project bundle", "discoverable", "configurable"), "Export"))
        add(descriptor("export.share.bridge", "Share Bridge", PluginCategory.EXPORT, listOf("share bridge", "discoverable", "configurable"), "Export"))
        add(descriptor("export.artifact.preview", "Artifact Preview", PluginCategory.EXPORT, listOf("artifact preview", "discoverable", "configurable"), "Export"))
        add(descriptor("export.export.queue", "Export Queue", PluginCategory.EXPORT, listOf("export queue", "discoverable", "configurable"), "Export"))
        add(descriptor("export.export.profiles", "Export Profiles", PluginCategory.EXPORT, listOf("export profiles", "discoverable", "configurable"), "Export"))
        add(descriptor("canvas.canvas.engine", "Canvas Engine", PluginCategory.CANVAS, listOf("canvas engine", "discoverable", "configurable"), "Canvas"))
        add(descriptor("canvas.layers", "Layers", PluginCategory.CANVAS, listOf("layers", "discoverable", "configurable"), "Canvas"))
        add(descriptor("canvas.brush.engine", "Brush Engine", PluginCategory.CANVAS, listOf("brush engine", "discoverable", "configurable"), "Canvas"))
        add(descriptor("canvas.shape.tools", "Shape Tools", PluginCategory.CANVAS, listOf("shape tools", "discoverable", "configurable"), "Canvas"))
        add(descriptor("canvas.gradient.engine", "Gradient Engine", PluginCategory.CANVAS, listOf("gradient engine", "discoverable", "configurable"), "Canvas"))
        add(descriptor("canvas.selection.engine", "Selection Engine", PluginCategory.CANVAS, listOf("selection engine", "discoverable", "configurable"), "Canvas"))
        add(descriptor("canvas.transform.engine", "Transform Engine", PluginCategory.CANVAS, listOf("transform engine", "discoverable", "configurable"), "Canvas"))
        add(descriptor("canvas.filter.lab", "Filter Lab", PluginCategory.CANVAS, listOf("filter lab", "discoverable", "configurable"), "Canvas"))
        add(descriptor("canvas.mask.engine", "Mask Engine", PluginCategory.CANVAS, listOf("mask engine", "discoverable", "configurable"), "Canvas"))
        add(descriptor("canvas.pattern.engine", "Pattern Engine", PluginCategory.CANVAS, listOf("pattern engine", "discoverable", "configurable"), "Canvas"))
        add(descriptor("canvas.symmetry", "Symmetry", PluginCategory.CANVAS, listOf("symmetry", "discoverable", "configurable"), "Canvas"))
        add(descriptor("canvas.canvas.snapshots", "Canvas Snapshots", PluginCategory.CANVAS, listOf("canvas snapshots", "discoverable", "configurable"), "Canvas"))
        add(descriptor("sculpt_3d.3d.sculpt", "3D Sculpt", PluginCategory.SCULPT_3D, listOf("3d sculpt", "discoverable", "configurable"), "Sculpt 3D"))
        add(descriptor("sculpt_3d.mesh.primitives", "Mesh Primitives", PluginCategory.SCULPT_3D, listOf("mesh primitives", "discoverable", "configurable"), "Sculpt 3D"))
        add(descriptor("sculpt_3d.sculpt.brushes", "Sculpt Brushes", PluginCategory.SCULPT_3D, listOf("sculpt brushes", "discoverable", "configurable"), "Sculpt 3D"))
        add(descriptor("sculpt_3d.mesh.materials", "Mesh Materials", PluginCategory.SCULPT_3D, listOf("mesh materials", "discoverable", "configurable"), "Sculpt 3D"))
        add(descriptor("sculpt_3d.mesh.transform", "Mesh Transform", PluginCategory.SCULPT_3D, listOf("mesh transform", "discoverable", "configurable"), "Sculpt 3D"))
        add(descriptor("sculpt_3d.scene.inspector", "Scene Inspector", PluginCategory.SCULPT_3D, listOf("scene inspector", "discoverable", "configurable"), "Sculpt 3D"))
        add(descriptor("sculpt_3d.mesh.history", "Mesh History", PluginCategory.SCULPT_3D, listOf("mesh history", "discoverable", "configurable"), "Sculpt 3D"))
        add(descriptor("sculpt_3d.viewport.tools", "Viewport Tools", PluginCategory.SCULPT_3D, listOf("viewport tools", "discoverable", "configurable"), "Sculpt 3D"))
        add(descriptor("sculpt_3d.lighting.presets", "Lighting Presets", PluginCategory.SCULPT_3D, listOf("lighting presets", "discoverable", "configurable"), "Sculpt 3D"))
        add(descriptor("sculpt_3d.camera.presets", "Camera Presets", PluginCategory.SCULPT_3D, listOf("camera presets", "discoverable", "configurable"), "Sculpt 3D"))
        add(descriptor("sculpt_3d.mesh.export", "Mesh Export", PluginCategory.SCULPT_3D, listOf("mesh export", "discoverable", "configurable"), "Sculpt 3D"))
        add(descriptor("sculpt_3d.scene.export", "Scene Export", PluginCategory.SCULPT_3D, listOf("scene export", "discoverable", "configurable"), "Sculpt 3D"))
        add(descriptor("productivity.notes", "Notes", PluginCategory.PRODUCTIVITY, listOf("notes", "discoverable", "configurable"), "Productivity"))
        add(descriptor("productivity.tasks", "Tasks", PluginCategory.PRODUCTIVITY, listOf("tasks", "discoverable", "configurable"), "Productivity"))
        add(descriptor("productivity.workspace.memory", "Workspace Memory", PluginCategory.PRODUCTIVITY, listOf("workspace memory", "discoverable", "configurable"), "Productivity"))
        add(descriptor("productivity.command.palette", "Command Palette", PluginCategory.PRODUCTIVITY, listOf("command palette", "discoverable", "configurable"), "Productivity"))
        add(descriptor("productivity.pinned.tools", "Pinned Tools", PluginCategory.PRODUCTIVITY, listOf("pinned tools", "discoverable", "configurable"), "Productivity"))
        add(descriptor("productivity.favorites", "Favorites", PluginCategory.PRODUCTIVITY, listOf("favorites", "discoverable", "configurable"), "Productivity"))
        add(descriptor("productivity.recent.items", "Recent Items", PluginCategory.PRODUCTIVITY, listOf("recent items", "discoverable", "configurable"), "Productivity"))
        add(descriptor("productivity.session.resume", "Session Resume", PluginCategory.PRODUCTIVITY, listOf("session resume", "discoverable", "configurable"), "Productivity"))
        add(descriptor("productivity.templates", "Templates", PluginCategory.PRODUCTIVITY, listOf("templates", "discoverable", "configurable"), "Productivity"))
        add(descriptor("productivity.quick.actions", "Quick Actions", PluginCategory.PRODUCTIVITY, listOf("quick actions", "discoverable", "configurable"), "Productivity"))
        add(descriptor("productivity.scratchpad", "Scratchpad", PluginCategory.PRODUCTIVITY, listOf("scratchpad", "discoverable", "configurable"), "Productivity"))
        add(descriptor("productivity.focus.mode", "Focus Mode", PluginCategory.PRODUCTIVITY, listOf("focus mode", "discoverable", "configurable"), "Productivity"))
        add(descriptor("web.web.search", "Web Search", PluginCategory.WEB, listOf("web search", "discoverable", "configurable"), "Web"))
        add(descriptor("web.html.fetcher", "HTML Fetcher", PluginCategory.WEB, listOf("html fetcher", "discoverable", "configurable"), "Web"))
        add(descriptor("web.readable.extraction", "Readable Extraction", PluginCategory.WEB, listOf("readable extraction", "discoverable", "configurable"), "Web"))
        add(descriptor("web.link.inspector", "Link Inspector", PluginCategory.WEB, listOf("link inspector", "discoverable", "configurable"), "Web"))
        add(descriptor("web.web.notes", "Web Notes", PluginCategory.WEB, listOf("web notes", "discoverable", "configurable"), "Web"))
        add(descriptor("web.research.sessions", "Research Sessions", PluginCategory.WEB, listOf("research sessions", "discoverable", "configurable"), "Web"))
        add(descriptor("web.source.capture", "Source Capture", PluginCategory.WEB, listOf("source capture", "discoverable", "configurable"), "Web"))
        add(descriptor("web.page.snapshot", "Page Snapshot", PluginCategory.WEB, listOf("page snapshot", "discoverable", "configurable"), "Web"))
        add(descriptor("web.domain.filters", "Domain Filters", PluginCategory.WEB, listOf("domain filters", "discoverable", "configurable"), "Web"))
        add(descriptor("web.search.history", "Search History", PluginCategory.WEB, listOf("search history", "discoverable", "configurable"), "Web"))
        add(descriptor("web.web.import", "Web Import", PluginCategory.WEB, listOf("web import", "discoverable", "configurable"), "Web"))
        add(descriptor("web.citation.capture", "Citation Capture", PluginCategory.WEB, listOf("citation capture", "discoverable", "configurable"), "Web"))
        add(descriptor("agent.agent.runtime", "Agent Runtime", PluginCategory.AGENT, listOf("agent runtime", "discoverable", "configurable"), "Agent"))
        add(descriptor("agent.planner", "Planner", PluginCategory.AGENT, listOf("planner", "discoverable", "configurable"), "Agent"))
        add(descriptor("agent.tool.router", "Tool Router", PluginCategory.AGENT, listOf("tool router", "discoverable", "configurable"), "Agent"))
        add(descriptor("agent.critic.pass", "Critic Pass", PluginCategory.AGENT, listOf("critic pass", "discoverable", "configurable"), "Agent"))
        add(descriptor("agent.repair.pass", "Repair Pass", PluginCategory.AGENT, listOf("repair pass", "discoverable", "configurable"), "Agent"))
        add(descriptor("agent.world.model", "World Model", PluginCategory.AGENT, listOf("world model", "discoverable", "configurable"), "Agent"))
        add(descriptor("agent.agent.memory", "Agent Memory", PluginCategory.AGENT, listOf("agent memory", "discoverable", "configurable"), "Agent"))
        add(descriptor("agent.task.queue", "Task Queue", PluginCategory.AGENT, listOf("task queue", "discoverable", "configurable"), "Agent"))
        add(descriptor("agent.multi.agent.roles", "Multi-Agent Roles", PluginCategory.AGENT, listOf("multi-agent roles", "discoverable", "configurable"), "Agent"))
        add(descriptor("agent.context.compiler", "Context Compiler", PluginCategory.AGENT, listOf("context compiler", "discoverable", "configurable"), "Agent"))
        add(descriptor("agent.execution.trace", "Execution Trace", PluginCategory.AGENT, listOf("execution trace", "discoverable", "configurable"), "Agent"))
        add(descriptor("agent.agent.policies", "Agent Policies", PluginCategory.AGENT, listOf("agent policies", "discoverable", "configurable"), "Agent"))
        add(descriptor("theme_ui.theme.studio", "Theme Studio", PluginCategory.THEME_UI, listOf("theme studio", "discoverable", "configurable"), "Theme Ui"))
        add(descriptor("theme_ui.dark.theme", "Dark Theme", PluginCategory.THEME_UI, listOf("dark theme", "discoverable", "configurable"), "Theme Ui"))
        add(descriptor("theme_ui.light.theme", "Light Theme", PluginCategory.THEME_UI, listOf("light theme", "discoverable", "configurable"), "Theme Ui"))
        add(descriptor("theme_ui.dynamic.color", "Dynamic Color", PluginCategory.THEME_UI, listOf("dynamic color", "discoverable", "configurable"), "Theme Ui"))
        add(descriptor("theme_ui.typography", "Typography", PluginCategory.THEME_UI, listOf("typography", "discoverable", "configurable"), "Theme Ui"))
        add(descriptor("theme_ui.density.controls", "Density Controls", PluginCategory.THEME_UI, listOf("density controls", "discoverable", "configurable"), "Theme Ui"))
        add(descriptor("theme_ui.motion.settings", "Motion Settings", PluginCategory.THEME_UI, listOf("motion settings", "discoverable", "configurable"), "Theme Ui"))
        add(descriptor("theme_ui.panel.layouts", "Panel Layouts", PluginCategory.THEME_UI, listOf("panel layouts", "discoverable", "configurable"), "Theme Ui"))
        add(descriptor("theme_ui.accent.editor", "Accent Editor", PluginCategory.THEME_UI, listOf("accent editor", "discoverable", "configurable"), "Theme Ui"))
        add(descriptor("theme_ui.accessibility.presets", "Accessibility Presets", PluginCategory.THEME_UI, listOf("accessibility presets", "discoverable", "configurable"), "Theme Ui"))
        add(descriptor("theme_ui.ui.profiles", "UI Profiles", PluginCategory.THEME_UI, listOf("ui profiles", "discoverable", "configurable"), "Theme Ui"))
        add(descriptor("theme_ui.workspace.chrome", "Workspace Chrome", PluginCategory.THEME_UI, listOf("workspace chrome", "discoverable", "configurable"), "Theme Ui"))
        add(descriptor("import_export.import.hub", "Import Hub", PluginCategory.IMPORT_EXPORT, listOf("import hub", "discoverable", "configurable"), "Import Export"))
        add(descriptor("import_export.archive.import", "Archive Import", PluginCategory.IMPORT_EXPORT, listOf("archive import", "discoverable", "configurable"), "Import Export"))
        add(descriptor("import_export.image.import", "Image Import", PluginCategory.IMPORT_EXPORT, listOf("image import", "discoverable", "configurable"), "Import Export"))
        add(descriptor("import_export.document.import", "Document Import", PluginCategory.IMPORT_EXPORT, listOf("document import", "discoverable", "configurable"), "Import Export"))
        add(descriptor("import_export.project.import", "Project Import", PluginCategory.IMPORT_EXPORT, listOf("project import", "discoverable", "configurable"), "Import Export"))
        add(descriptor("import_export.batch.import", "Batch Import", PluginCategory.IMPORT_EXPORT, listOf("batch import", "discoverable", "configurable"), "Import Export"))
        add(descriptor("import_export.migration.wizard", "Migration Wizard", PluginCategory.IMPORT_EXPORT, listOf("migration wizard", "discoverable", "configurable"), "Import Export"))
        add(descriptor("import_export.export.hub", "Export Hub", PluginCategory.IMPORT_EXPORT, listOf("export hub", "discoverable", "configurable"), "Import Export"))
        add(descriptor("import_export.project.archive", "Project Archive", PluginCategory.IMPORT_EXPORT, listOf("project archive", "discoverable", "configurable"), "Import Export"))
        add(descriptor("import_export.settings.backup", "Settings Backup", PluginCategory.IMPORT_EXPORT, listOf("settings backup", "discoverable", "configurable"), "Import Export"))
        add(descriptor("import_export.workspace.backup", "Workspace Backup", PluginCategory.IMPORT_EXPORT, listOf("workspace backup", "discoverable", "configurable"), "Import Export"))
        add(descriptor("import_export.cross.version.restore", "Cross-Version Restore", PluginCategory.IMPORT_EXPORT, listOf("cross-version restore", "discoverable", "configurable"), "Import Export"))
        add(descriptor("database.workspace.database", "Workspace Database", PluginCategory.DATABASE, listOf("workspace database", "discoverable", "configurable"), "Database"))
        add(descriptor("database.chat.storage", "Chat Storage", PluginCategory.DATABASE, listOf("chat storage", "discoverable", "configurable"), "Database"))
        add(descriptor("database.artifact.storage", "Artifact Storage", PluginCategory.DATABASE, listOf("artifact storage", "discoverable", "configurable"), "Database"))
        add(descriptor("database.memory.storage", "Memory Storage", PluginCategory.DATABASE, listOf("memory storage", "discoverable", "configurable"), "Database"))
        add(descriptor("database.project.storage", "Project Storage", PluginCategory.DATABASE, listOf("project storage", "discoverable", "configurable"), "Database"))
        add(descriptor("database.version.history", "Version History", PluginCategory.DATABASE, listOf("version history", "discoverable", "configurable"), "Database"))
        add(descriptor("database.database.inspector", "Database Inspector", PluginCategory.DATABASE, listOf("database inspector", "discoverable", "configurable"), "Database"))
        add(descriptor("database.storage.stats", "Storage Stats", PluginCategory.DATABASE, listOf("storage stats", "discoverable", "configurable"), "Database"))
        add(descriptor("database.migration.monitor", "Migration Monitor", PluginCategory.DATABASE, listOf("migration monitor", "discoverable", "configurable"), "Database"))
        add(descriptor("database.backup.index", "Backup Index", PluginCategory.DATABASE, listOf("backup index", "discoverable", "configurable"), "Database"))
        add(descriptor("database.cache.index", "Cache Index", PluginCategory.DATABASE, listOf("cache index", "discoverable", "configurable"), "Database"))
        add(descriptor("database.integrity.checker", "Integrity Checker", PluginCategory.DATABASE, listOf("integrity checker", "discoverable", "configurable"), "Database"))
        add(descriptor("media.media.pipeline", "Media Pipeline", PluginCategory.MEDIA, listOf("media pipeline", "discoverable", "configurable"), "Media"))
        add(descriptor("media.camera.capture", "Camera Capture", PluginCategory.MEDIA, listOf("camera capture", "discoverable", "configurable"), "Media"))
        add(descriptor("media.video.capture", "Video Capture", PluginCategory.MEDIA, listOf("video capture", "discoverable", "configurable"), "Media"))
        add(descriptor("media.audio.capture", "Audio Capture", PluginCategory.MEDIA, listOf("audio capture", "discoverable", "configurable"), "Media"))
        add(descriptor("media.media.playback", "Media Playback", PluginCategory.MEDIA, listOf("media playback", "discoverable", "configurable"), "Media"))
        add(descriptor("media.thumbnail.generator", "Thumbnail Generator", PluginCategory.MEDIA, listOf("thumbnail generator", "discoverable", "configurable"), "Media"))
        add(descriptor("media.exif.inspector", "EXIF Inspector", PluginCategory.MEDIA, listOf("exif inspector", "discoverable", "configurable"), "Media"))
        add(descriptor("media.media.organizer", "Media Organizer", PluginCategory.MEDIA, listOf("media organizer", "discoverable", "configurable"), "Media"))
        add(descriptor("media.frame.extractor", "Frame Extractor", PluginCategory.MEDIA, listOf("frame extractor", "discoverable", "configurable"), "Media"))
        add(descriptor("media.media.compressor", "Media Compressor", PluginCategory.MEDIA, listOf("media compressor", "discoverable", "configurable"), "Media"))
        add(descriptor("media.media.import", "Media Import", PluginCategory.MEDIA, listOf("media import", "discoverable", "configurable"), "Media"))
        add(descriptor("media.media.share", "Media Share", PluginCategory.MEDIA, listOf("media share", "discoverable", "configurable"), "Media"))
        add(descriptor("automation.automation.engine", "Automation Engine", PluginCategory.AUTOMATION, listOf("automation engine", "discoverable", "configurable"), "Automation"))
        add(descriptor("automation.batch.actions", "Batch Actions", PluginCategory.AUTOMATION, listOf("batch actions", "discoverable", "configurable"), "Automation"))
        add(descriptor("automation.scheduled.jobs", "Scheduled Jobs", PluginCategory.AUTOMATION, listOf("scheduled jobs", "discoverable", "configurable"), "Automation"))
        add(descriptor("automation.macro.recorder", "Macro Recorder", PluginCategory.AUTOMATION, listOf("macro recorder", "discoverable", "configurable"), "Automation"))
        add(descriptor("automation.workflow.builder", "Workflow Builder", PluginCategory.AUTOMATION, listOf("workflow builder", "discoverable", "configurable"), "Automation"))
        add(descriptor("automation.trigger.rules", "Trigger Rules", PluginCategory.AUTOMATION, listOf("trigger rules", "discoverable", "configurable"), "Automation"))
        add(descriptor("automation.action.chains", "Action Chains", PluginCategory.AUTOMATION, listOf("action chains", "discoverable", "configurable"), "Automation"))
        add(descriptor("automation.retry.policies", "Retry Policies", PluginCategory.AUTOMATION, listOf("retry policies", "discoverable", "configurable"), "Automation"))
        add(descriptor("automation.job.history", "Job History", PluginCategory.AUTOMATION, listOf("job history", "discoverable", "configurable"), "Automation"))
        add(descriptor("automation.queue.manager", "Queue Manager", PluginCategory.AUTOMATION, listOf("queue manager", "discoverable", "configurable"), "Automation"))
        add(descriptor("automation.template.runner", "Template Runner", PluginCategory.AUTOMATION, listOf("template runner", "discoverable", "configurable"), "Automation"))
        add(descriptor("automation.automation.logs", "Automation Logs", PluginCategory.AUTOMATION, listOf("automation logs", "discoverable", "configurable"), "Automation"))
        add(descriptor("security.encrypted.keys", "Encrypted Keys", PluginCategory.SECURITY, listOf("encrypted keys", "discoverable", "configurable"), "Security"))
        add(descriptor("security.credential.scoping", "Credential Scoping", PluginCategory.SECURITY, listOf("credential scoping", "discoverable", "configurable"), "Security"))
        add(descriptor("security.sandbox.policy", "Sandbox Policy", PluginCategory.SECURITY, listOf("sandbox policy", "discoverable", "configurable"), "Security"))
        add(descriptor("security.file.safety", "File Safety", PluginCategory.SECURITY, listOf("file safety", "discoverable", "configurable"), "Security"))
        add(descriptor("security.path.guard", "Path Guard", PluginCategory.SECURITY, listOf("path guard", "discoverable", "configurable"), "Security"))
        add(descriptor("security.command.guard", "Command Guard", PluginCategory.SECURITY, listOf("command guard", "discoverable", "configurable"), "Security"))
        add(descriptor("security.permission.gate", "Permission Gate", PluginCategory.SECURITY, listOf("permission gate", "discoverable", "configurable"), "Security"))
        add(descriptor("security.secret.redaction", "Secret Redaction", PluginCategory.SECURITY, listOf("secret redaction", "discoverable", "configurable"), "Security"))
        add(descriptor("security.backup.encryption", "Backup Encryption", PluginCategory.SECURITY, listOf("backup encryption", "discoverable", "configurable"), "Security"))
        add(descriptor("security.session.lock", "Session Lock", PluginCategory.SECURITY, listOf("session lock", "discoverable", "configurable"), "Security"))
        add(descriptor("security.integrity.monitor", "Integrity Monitor", PluginCategory.SECURITY, listOf("integrity monitor", "discoverable", "configurable"), "Security"))
        add(descriptor("security.audit.log", "Audit Log", PluginCategory.SECURITY, listOf("audit log", "discoverable", "configurable"), "Security"))
        add(descriptor("networking.http.client", "HTTP Client", PluginCategory.NETWORKING, listOf("http client", "discoverable", "configurable"), "Networking"))
        add(descriptor("networking.websocket.bridge", "WebSocket Bridge", PluginCategory.NETWORKING, listOf("websocket bridge", "discoverable", "configurable"), "Networking"))
        add(descriptor("networking.request.inspector", "Request Inspector", PluginCategory.NETWORKING, listOf("request inspector", "discoverable", "configurable"), "Networking"))
        add(descriptor("networking.connection.monitor", "Connection Monitor", PluginCategory.NETWORKING, listOf("connection monitor", "discoverable", "configurable"), "Networking"))
        add(descriptor("networking.retry.controller", "Retry Controller", PluginCategory.NETWORKING, listOf("retry controller", "discoverable", "configurable"), "Networking"))
        add(descriptor("networking.timeout.manager", "Timeout Manager", PluginCategory.NETWORKING, listOf("timeout manager", "discoverable", "configurable"), "Networking"))
        add(descriptor("networking.offline.queue", "Offline Queue", PluginCategory.NETWORKING, listOf("offline queue", "discoverable", "configurable"), "Networking"))
        add(descriptor("networking.network.profiles", "Network Profiles", PluginCategory.NETWORKING, listOf("network profiles", "discoverable", "configurable"), "Networking"))
        add(descriptor("networking.traffic.diagnostics", "Traffic Diagnostics", PluginCategory.NETWORKING, listOf("traffic diagnostics", "discoverable", "configurable"), "Networking"))
        add(descriptor("networking.endpoint.health", "Endpoint Health", PluginCategory.NETWORKING, listOf("endpoint health", "discoverable", "configurable"), "Networking"))
        add(descriptor("networking.download.manager", "Download Manager", PluginCategory.NETWORKING, listOf("download manager", "discoverable", "configurable"), "Networking"))
        add(descriptor("networking.upload.manager", "Upload Manager", PluginCategory.NETWORKING, listOf("upload manager", "discoverable", "configurable"), "Networking"))
        add(descriptor("document.document.handler", "Document Handler", PluginCategory.DOCUMENT, listOf("document handler", "discoverable", "configurable"), "Document"))
        add(descriptor("document.pdf.reader", "PDF Reader", PluginCategory.DOCUMENT, listOf("pdf reader", "discoverable", "configurable"), "Document"))
        add(descriptor("document.pdf.export", "PDF Export", PluginCategory.DOCUMENT, listOf("pdf export", "discoverable", "configurable"), "Document"))
        add(descriptor("document.docx.builder", "DOCX Builder", PluginCategory.DOCUMENT, listOf("docx builder", "discoverable", "configurable"), "Document"))
        add(descriptor("document.markdown.renderer", "Markdown Renderer", PluginCategory.DOCUMENT, listOf("markdown renderer", "discoverable", "configurable"), "Document"))
        add(descriptor("document.html.export", "HTML Export", PluginCategory.DOCUMENT, listOf("html export", "discoverable", "configurable"), "Document"))
        add(descriptor("document.text.import", "Text Import", PluginCategory.DOCUMENT, listOf("text import", "discoverable", "configurable"), "Document"))
        add(descriptor("document.document.preview", "Document Preview", PluginCategory.DOCUMENT, listOf("document preview", "discoverable", "configurable"), "Document"))
        add(descriptor("document.document.metadata", "Document Metadata", PluginCategory.DOCUMENT, listOf("document metadata", "discoverable", "configurable"), "Document"))
        add(descriptor("document.document.packager", "Document Packager", PluginCategory.DOCUMENT, listOf("document packager", "discoverable", "configurable"), "Document"))
        add(descriptor("document.document.search", "Document Search", PluginCategory.DOCUMENT, listOf("document search", "discoverable", "configurable"), "Document"))
        add(descriptor("document.document.conversion", "Document Conversion", PluginCategory.DOCUMENT, listOf("document conversion", "discoverable", "configurable"), "Document"))
        add(descriptor("other.diagnostics", "Diagnostics", PluginCategory.OTHER, listOf("diagnostics", "discoverable", "configurable"), "Other"))
        add(descriptor("other.feature.audit", "Feature Audit", PluginCategory.OTHER, listOf("feature audit", "discoverable", "configurable"), "Other"))
        add(descriptor("other.health.center", "Health Center", PluginCategory.OTHER, listOf("health center", "discoverable", "configurable"), "Other"))
        add(descriptor("other.performance.monitor", "Performance Monitor", PluginCategory.OTHER, listOf("performance monitor", "discoverable", "configurable"), "Other"))
        add(descriptor("other.memory.monitor", "Memory Monitor", PluginCategory.OTHER, listOf("memory monitor", "discoverable", "configurable"), "Other"))
        add(descriptor("other.storage.monitor", "Storage Monitor", PluginCategory.OTHER, listOf("storage monitor", "discoverable", "configurable"), "Other"))
        add(descriptor("other.release.inspector", "Release Inspector", PluginCategory.OTHER, listOf("release inspector", "discoverable", "configurable"), "Other"))
        add(descriptor("other.capability.matrix", "Capability Matrix", PluginCategory.OTHER, listOf("capability matrix", "discoverable", "configurable"), "Other"))
        add(descriptor("other.plugin.diagnostics", "Plugin Diagnostics", PluginCategory.OTHER, listOf("plugin diagnostics", "discoverable", "configurable"), "Other"))
        add(descriptor("other.tool.diagnostics", "Tool Diagnostics", PluginCategory.OTHER, listOf("tool diagnostics", "discoverable", "configurable"), "Other"))
        add(descriptor("other.workspace.scanner", "Workspace Scanner", PluginCategory.OTHER, listOf("workspace scanner", "discoverable", "configurable"), "Other"))
        add(descriptor("other.system.report", "System Report", PluginCategory.OTHER, listOf("system report", "discoverable", "configurable"), "Other"))
        addAll(expansion())
    }


    /** Extended first-party contract surface. These descriptors are intentionally
     * discoverable capability modules rather than fake marketplace listings. The
     * concrete runtime owns the actions; these contracts make feature coverage
     * machine-auditable and ready for independent module implementations. */
    private fun expansion(): List<PluginDescriptor> {
        val names = listOf(
            "Inspector", "Profiler", "Batch Runner", "Preset Engine", "History Lens",
            "Schema Guard", "Diff Engine", "Cache Layer", "Recovery Manager", "Telemetry Guard",
            "Import Wizard", "Export Wizard", "Preview Engine", "Validation Gate", "Permission Broker",
            "Queue Orchestrator", "Snapshot Engine", "State Reconciler", "Conflict Resolver", "Index Builder",
            "Search Index", "Dependency Resolver", "Capability Router", "Session Manager", "Context Manager",
            "Prompt Compiler", "Response Validator", "Output Normalizer", "Artifact Inspector", "Package Verifier",
            "Model Evaluator", "Provider Health", "Rate Limit Guard", "Offline Fallback", "Error Recovery",
            "Task Planner", "Task Runner", "Event Bus", "Command Palette", "Workspace Lens", "Project Auditor"
        )
        return PluginCategory.entries.flatMap { category ->
            names.mapIndexed { index, label ->
                descriptor(
                    id = "expanded.contracts.${category.name.lowercase()}.$index",
                    name = "${category.name.replace('_', ' ').lowercase().replaceFirstChar { it.uppercase() }} $label",
                    category = category,
                    capabilities = listOf("discoverable", "diagnosable", "versioned", "dependency-aware"),
                    family = "Extended ${category.name.lowercase()} capability",
                )
            }
        }
    }


    private fun descriptor(id: String, name: String, category: PluginCategory, capabilities: List<String>, family: String): PluginDescriptor =
        PluginDescriptor(id, name, category, "2.0.0", "$name • $family capability", capabilities = capabilities)
}
